This Dockerfile can be used to run any necessary command-line operations
in order to build the app with the current module as needed.
Only really necessary for specific deployment types, but present if necessary.